### ISSUE TITLE
Ligit does nothing

### ISSUE THREAD

**Issue by Bucky420** [ModdedMinecraft/BetterChunkLoader#6]
i looked at sponge it said its loaded no commands work no error in the logs i looked hard ...

**Comment by leelawd** [comment]
What version of sponge are you using?

**Comment by Bucky420** [comment]
the latest 3340

**Comment by leelawd** [comment]
I can't seem to replicate the issue :( my test setup running the latest (now 3341) works fine D:
could you possibly send me a debug.log after attempting to load this?

**Comment by Bucky420** [comment]
yes 
[latest.log](https://github.com/ModdedMinecraft/BetterChunkLoader/files/2221484/latest.log)

**Comment by Bucky420** [comment]
wow that file exists derp ... 
[debug.log](https://github.com/ModdedMinecraft/BetterChunkLoader/files/2221491/debug.log)


```
[Server thread/ERROR] [Sponge]: Could not pass FMLServerAboutToStartEvent to Plugin{id=betterchunkloader, name=BetterChunkLoader, version=1.2.4, description=Fork of ShadowKittens Sponge port of KaiKikuchi's BetterChunkLoader plugin., authors=[leelawd93], source=/home/ntg/con/./plugins/BetterChunkLoader-1.2.4.jar}
java.lang.IllegalArgumentException: Configuration does not accept objects of type class net.moddedminecraft.betterchunkloader.config.CoreConfig
	at ninja.leaping.configurate.ScalarConfigValue.setValue(ScalarConfigValue.java:51) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3340.jar:1.12.2-2705-7.1.0-BETA-3340]
	at ninja.leaping.configurate.SimpleConfigurationNode.insertNewValue(SimpleConfigurationNode.java:311) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3340.jar:1.12.2-2705-7.1.0-BETA-3340]
	at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:276) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3340.jar:1.12.2-2705-7.1.0-BETA-3340]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:87) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3340.jar:1.12.2-2705-7.1.0-BETA-3340]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:33) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3340.jar:1.12.2-2705-7.1.0-BETA-3340]
	at ninja.leaping.configurate.SimpleConfigurationNode.storeDefault(SimpleConfigurationNode.java:117) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3340.jar:1.12.2-2705-7.1.0-BETA-3340]
	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:200) ~[spongeforge-1.12.2-2705-7.1.0-BETA-3340.jar:1.12.2-2705-7.1.0-BETA-3340]
	at net.moddedminecraft.betterchunkloader.config.Config.loadCore(Config.java:36) ~[Config.class:?]
	at net.moddedminecraft.betterchunkloader.BetterChunkLoader.onServerAboutStart(BetterChunkLoader.java:96) ~[BetterChunkLoader.class:?]
	at org.spongepowered.common.event.listener.GameAboutToStartServerEventListener_BetterChunkLoader_onServerAboutStart20.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~
```
this is what ur looking for?

**Comment by leelawd** [comment]
ok perfect, ill look into why its doing that. Thank you.

**Comment by leelawd** [comment]
https://github.com/ModdedMinecraft/BetterChunkLoader/releases/tag/1.2.5

This should be fixed now.
